### ISSUE TITLE
`lace help` provides incorrect description of `lace run` command

### ISSUE THREAD

**Issue by dxrcy** [rozukke/lace#27]
```
Commands:
run     Run text `.asm` or binary `.lc3` file directly and output to terminal
```
This line of the help message implies that a `.lc3` binary file can be executed with `lace run`, however `lace` tries to assemble the binary file. The code suggests this is intended behavour. Perhaps this is unimplemented?

**Comment by rozukke** [comment]
Will be implemented, thanks for the catch.
